In [1]:
import os
import pyodbc
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
import warnings
warnings.filterwarnings('ignore')


# Cargar archivo .env
# Ruta relativa desde el notebook hasta el .env
dotenv_path = '../generadores/.env'  #

# Cargar el archivo .env desde la ruta especificada
load_dotenv(dotenv_path=dotenv_path)

# Leer variables de entorno
username = os.getenv("USUARIO_DB")
password = os.getenv("CLAVE_BD")

# Validar que se cargaron bien
#print("Usuario:", username)
#print("Contraseña cargada:", bool(password))  # No imprime la clave, pero verifica si existe

if not username or not password:
    raise ValueError("Las variables de entorno USUARIO_DB o CLAVE_BD no están definidas")

# Cadena de conexión
conn_str = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=upgradeserver-vf.database.windows.net;'
    'DATABASE=Banco;'
    f'UID={username};'
    f'PWD={password}'
)

# Conexión
conn = pyodbc.connect(conn_str)

In [2]:
query_usuarios = "SELECT * FROM usuarios" 
df_usuarios = pd.read_sql(query_usuarios, conn)
df_usuarios.head()

,id,nombre,apellido,estado_civil,dni,nacionalidad,fecha_nacimiento,direccion,codigo_postal,provincia,telefono,email,es_moroso,profesion,salario,numero_cuenta,tipo_cuenta,saldo,antiguedad_cliente,genero
0,42654,Consuelo,Sales,Casada,94923570V,Belga,1987-01-27,"Urbanización Delia Lobo 4 Puerta 2 , Palencia,...",25144,Jaén,635107240,nandotoro@example.net,False,"Empleado de servicios estadísticos, financiero...",5135.43,ES7032903890966775197447,corriente,43181.42,2021-01-23,Femenino
1,42655,Crescencia,Quesada,Divorciada,36901068Y,Indonesia,1954-11-02,"Rambla de Epifanio Azorin 4, Lleida, 17091",50678,Cáceres,633439627,marta79@example.org,False,Planchador manuales,7202.31,ES2005191248797654536134,corriente,87041.87,2021-02-01,Femenino
2,42656,Malena,Gordillo,Divorciada,22368636D,Indonesia,1984-02-18,"Vial de Miguel Ángel Zamorano 19 Apt. 99 , Tol...",31539,Jaén,693962009,sebastian16@example.com,False,Pescador de alta mar,6435.71,ES0484741416708329980787,corriente,44805.74,2024-12-18,Femenino
3,42657,Ofelia,Quevedo,Viuda,63161733F,Afgana,2005-05-27,"Avenida de Almudena Ribas 38 Puerta 3 , Madrid...",07591,Alicante,649011413,borjaromero@example.net,False,Pintor y empapelador,5615.52,ES6542893922000595866797,corriente,23457.44,2020-08-25,Femenino
4,42658,Eutimio,Cifuentes,Viudo,27733140Q,Singapurense,1961-07-14,"Avenida de Amelia Diego 4 Piso 8 , Tarragona, ...",28347,Huesca,772759266,mros@example.net,True,Director de explotaciones de minería,7486.86,ES4851800820155687571492,corriente,87971.60,2021-10-16,Masculino

In [3]:
df_usuarios.duplicated().sum() #comprueba si hay duplicados

np.int64(0)

In [4]:
df_usuarios.isnull().sum() #comprueba si hay valores nulos

id                    0
nombre                0
apellido              0
estado_civil          0
dni                   0
nacionalidad          0
fecha_nacimiento      0
direccion             0
codigo_postal         0
provincia             0
telefono              0
email                 0
es_moroso             0
profesion             0
salario               0
numero_cuenta         0
tipo_cuenta           0
saldo                 0
antiguedad_cliente    0
genero                0
dtype: int64

In [5]:
df_usuarios.dtypes

id                      int64
nombre                 object
apellido               object
estado_civil           object
dni                    object
nacionalidad           object
fecha_nacimiento       object
direccion              object
codigo_postal          object
provincia              object
telefono               object
email                  object
es_moroso                bool
profesion              object
salario               float64
numero_cuenta          object
tipo_cuenta            object
saldo                 float64
antiguedad_cliente     object
genero                 object
dtype: object

In [6]:
query_activos = "SELECT * FROM activos_financieros" 
df_activos = pd.read_sql(query_activos, conn)
df_activos.head()

   id  usuario_id  tipo_activo          descripcion      monto
0   1       52977       ahorro  Activos financieros    2988.57
1   2       52977       ahorro  Activos financieros    2988.57
2   3       43639       ahorro  Activos financieros   22709.47
3   4       49905  inversiones  Activos financieros  222459.66
4   5       52628       ahorro  Activos financieros   59254.00

In [7]:
df_activos.duplicated().sum() #comprueba si hay duplicados

np.int64(0)

In [8]:
df_activos.isnull().sum() #comprueba si hay valores nulos

id             0
usuario_id     0
tipo_activo    0
descripcion    0
monto          0
dtype: int64

In [9]:
df_activos.dtypes

id               int64
usuario_id       int64
tipo_activo     object
descripcion     object
monto          float64
dtype: object

In [10]:
query_creditos = "SELECT * FROM creditos" 
df_creditos = pd.read_sql(query_creditos, conn)
df_creditos.head()

   id  usuario_id     monto fecha_inicio   fecha_fin  estado         tipo
0   3       43598  30688.34   2021-07-14  2023-07-04  Moroso     Personal
1   4       51088  38568.26   2020-10-19  2021-10-14  Activo  Estudiantil
2   5       51349  32247.04   2022-12-05  2023-11-30  Pagado     Personal
3   6       47016  38042.53   2022-09-02  2026-08-12  Moroso  Estudiantil
4   7       52754  25469.67   2022-06-27  2023-06-22  Moroso   Automotriz

In [11]:
df_creditos.duplicated().sum() #comprueba si hay duplicados

np.int64(0)

In [12]:
df_creditos.isnull().sum() #comprueba si hay valores nulos

id              0
usuario_id      0
monto           0
fecha_inicio    0
fecha_fin       0
estado          0
tipo            0
dtype: int64

In [13]:
df_creditos.dtypes

id                int64
usuario_id        int64
monto           float64
fecha_inicio     object
fecha_fin        object
estado           object
tipo             object
dtype: object

In [14]:
#cambiamos fecha_inicio y fecha_fin a datetime
df_creditos['fecha_inicio'] = pd.to_datetime(df_creditos['fecha_inicio'])
df_creditos['fecha_fin'] = pd.to_datetime(df_creditos['fecha_fin'])

In [15]:
query_cuentas = "SELECT * FROM cuentas_bancarias" 
df_cuentas = pd.read_sql(query_cuentas, conn)
df_cuentas.head()

   id  usuario_id             numero_cuenta tipo_cuenta     saldo
0   1       48426  ES5466195092482025451168     empresa  64902.57
1   2       42851  ES9562496935527023658944      nómina  73824.23
2   3       53683  ES5986064142134058506669      ahorro   2067.07
3   4       42950  ES7928154194255986681000     empresa  64126.29
4   5       53681  ES7420859879834314564248      nómina  56563.96

In [16]:
df_cuentas.isnull().sum() #comprueba si hay valores nulos

id               0
usuario_id       0
numero_cuenta    0
tipo_cuenta      0
saldo            0
dtype: int64

In [17]:
df_cuentas.duplicated().sum() #comprueba si hay duplicados

np.int64(0)

In [18]:
df_cuentas.dtypes

id                 int64
usuario_id         int64
numero_cuenta     object
tipo_cuenta       object
saldo            float64
dtype: object

In [19]:
query_monedas = "SELECT * FROM monedas_digitales" 
df_monedas = pd.read_sql(query_monedas, conn)
df_monedas.head()

   id  usuario_id tipo_moneda     cantidad  valor_actual
0   1       49091         ADA  8727.795885          0.79
1   2       44497         BTC     1.137435      56869.56
2   3       49789         BTC     0.479071      50116.50
3   4       49918         BNB     8.197204        471.77
4   5       48010         XRP  3503.149303          0.84

In [20]:
df_monedas.duplicated().sum() #comprueba si hay duplicados

np.int64(0)

In [21]:
df_monedas.isnull().sum() #comprueba si hay valores nulos

id              0
usuario_id      0
tipo_moneda     0
cantidad        0
valor_actual    0
dtype: int64

In [22]:
df_monedas.dtypes

id                int64
usuario_id        int64
tipo_moneda      object
cantidad        float64
valor_actual    float64
dtype: object